[package]
name = "rust_qt_binding_generator"
version = "0.1.0"
authors = ["Jos van den Oever <jos@vandenoever.info>"]

[dependencies]
clap = "2"
regex= "1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
